fix the version check on the workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -19,9 +19,9 @@ jobs:
         run: yarn install --frozen-lockfile
       - name: Ensure that "lerna version" has been run
         run: |
-          changed=$(yarn run changed || echo "")
+          changed=$(yarn run --silent changed)
           if [ -n "$changed" ]; then
-            echo "Error: Found changed packages. Please run 'lerna version' before pushing changes." >&2
+            echo "Error: Found changed packages. Please run 'yarn run version' before pushing changes." >&2
             exit 1
           fi
       - name: Publish package on NPM 📦
